# Generated by Django 4.0.6 on 2022-08-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_rename_user_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='about',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='website',
            field=models.URLField(max_length=100),
        ),
    ]
